### ISSUE TITLE
小白一个，最新的OP源码报错

### ISSUE THREAD

**Issue by 467815891a** [kuoruan/luci-app-adbyby#1]
make[3]: Entering directory '/home/wei/openwrt/package/utils/.fr-CWgos9'
mkdir -p /home/wei/openwrt/bin/ar71xx/packages /home/wei/openwrt/build_dir/target-mips_34kc_musl-1.1.14/adbyby-2.7/ipkg-ar71xx/adbyby/CONTROL /home/wei/openwrt/staging_dir/target-mips_34kc_musl-1.1.14/pkginfo
install -d -m0755 /home/wei/openwrt/build_dir/target-mips_34kc_musl-1.1.14/adbyby-2.7/ipkg-ar71xx/adbyby/usr/share/adbyby
install -m0755 ./files/adbyby.sh /home/wei/openwrt/build_dir/target-mips_34kc_musl-1.1.14/adbyby-2.7/ipkg-ar71xx/adbyby/usr/share/adbyby/
install: cannot stat './files/adbyby.sh': No such file or directory
Makefile:70: recipe for target '/home/wei/openwrt/bin/ar71xx/packages/base/adbyby_2.7-20160110_ar71xx.ipk' failed

**Comment by kuoruan** [comment]
提示说 `./files/adbyby.sh`未找到，你检查一下你的目录结构？

**Comment by 467815891a** [comment]
我将adbyby文件夹放进package，adbyby里面有Makefile和files文件夹，adbyby.sh确实在里面。

**Comment by kuoruan** [comment]
你试试将adbyby文件夹放到 `package` 下，然后删除 openwrt 目录下的 tmp 文件夹，`./scripts/feeds install -a`，最后 `make package/adbyby/compile V=99`

**Comment by 467815891a** [comment]
make package/adbyby/compile V=99
Collecting package info: done
make[1]: Entering directory '/home/wei/openwrt'
make[1]: **\* No rule to make target 'package/adbyby/compile'.  Stop.
make[1]: Leaving directory '/home/wei/openwrt'
/home/wei/openwrt/include/toplevel.mk:192: recipe for target 'package/adbyby/compile' failed
make: **\* [package/adbyby/compile] Error 2
命令有问题？

**Comment by kuoruan** [comment]
哦，想起来了，compile没定义，需要直接 make package/adbyby/install V=99
这样吧，你加我QQ 11000443，我远程给你看看

**Comment by 467815891a** [comment]
搞定了，终于编过了，确实冲突了，重新同步源码就好了，谢谢
