### ISSUE TITLE
编译luci app问题

### ISSUE THREAD

**Issue by Eveink** [kuoruan/luci-app-adbyby#2]
我下载的SDK的根下没有luci/application这种目录，倒是更新feed以后在feeds目录里有，把adbyby的luci app目录放进去feeds/luci/application然后make menuconfig找不到这个包

**Comment by kuoruan** [comment]
恩，就是 feed 目录下，放进去之后，先 rm -rf tmp，然后运行一下更新软件包

```
./scripts/feeds/update -a
./scripts/feeds/install -a
```

**Comment by planktonzp** [comment]
lede版本编译luci时报错 
make[1]: Entering directory `/rzp/lede-sdk-ramips-mt7620_gcc-5.4.0_musl.Linux-x86_64'
make[1]: *** No rule to make target `feeds/luci/applications/luci-app-adbyby/compile'.  Stop.
make[1]: Leaving directory `/rzp/lede-sdk-ramips-mt7620_gcc-5.4.0_musl.Linux-x86_64'
make: *** [feeds/luci/applications/luci-app-adbyby/compile] Error 2

**Comment by kuoruan** [comment]
@ruizhipeng luci-app-adbyby 文件夹放 feeds/luci/application 目录下

**Comment by cnpcshangbo** [comment]
@kuoruan You have a typo.
The command should be
```
./scripts/feeds update -a
./scripts/feeds install -a
```

**Comment by cnpcshangbo** [comment]
This is a better tutorial. Hope the readme can be updated.
https://iteachs.com/?post=25
